### ISSUE TITLE
Create a "Get Involved" section

### ISSUE THREAD

**Issue by andrewjong** [sjsumlclub/Website#6]
Show clearly how people can get involved immediately. Such as by attending meetings and joining our Slack.

Additionally, state clearly the requirements to become an official member.

> Complete one from below per semester:
> - Attend at least 3 meetings and 2/3 of remaining meetings.
> - Lead 1 meeting or help us create 3 meetings (meetings could be workshops, reading discussions, scheduling a guest presentation, etc.)
> - Take part in a club project (e.g. find teammates for your CS 297/298 project!). Includes short biweekly updates on project progress.

Members can benefit from club funds for their project and be featured on our website as an official member.

**Comment by tintheanh** [comment]
So we are going to clearly state these 3 bullet points in this Get Inolved section?  And where do you want it to be placed?

**Comment by andrewjong** [comment]
- Attend 2/3 of meetings (at least 3).
- Lead 1 meeting or help officers create 2 meetings (meetings could be workshops, reading discussions, scheduling a guest presentation, etc.)
- Take part in a club project (e.g. find teammates for your CS 297/298 project!). Includes short biweekly updates on project progress.

**Comment by andrewjong** [comment]
Get Involved should come right after Team

**Comment by andrewjong** [comment]
Can we also rename "Team" to "Official Team Members"? That way it's clear these are just the people who met the official requirements.
