### ISSUE TITLE
Allow Reordering of Entries in Strapi CMS

### ISSUE THREAD

**Issue by andrewjong** [sjsumlclub/Website#9]
Currently the order of schedule/members cannot be changed. Is there a way to allow reordering? Thanks!

**Comment by tintheanh** [comment]
Since Strapi does not support entries reordering. One workaround I can think of is adding "order" field to each entry data and have Strapi to sort them based on this "order".

**Comment by andrewjong** [comment]
sounds good

**Comment by andrewjong** [comment]
Can we also allow reordering of the carousel images?
